[build]
command = "npm run build"
publish = "dist"
functions = "functions"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_VERSION = "18" 