[build]
  command = "cd backend && npm install"
  publish = "backend"
  functions = "backend/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 