[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 